### ISSUE TITLE
Few problems when trying to launch the project locally

### ISSUE THREAD

**Issue by zedonglim** [LIAAD/physio#2]
Hi, I have cloned the projects and tried to run it on my local machine, but I met few problems, if you may clarify or help me to solve the issues, it would be highly appreciated.

First, regarding the Dockerfile in /backend/flask:

COPY cert.crt .
COPY cert.key .

if I comment both of these, will it have any affect on running the whole projects? As during the first time when I tried to run docker-compose up --build, I get this error:

---
 => ERROR [flask 4/7] COPY cert.crt .                                                                              0.0s
 => ERROR [flask 5/7] COPY cert.key .                                                                              0.0s
 > [flask 4/7] COPY cert.crt .:
 > [flask 5/7] COPY cert.key .:
failed to solve: failed to compute cache key: failed to calculate checksum of ref 3f7044dc-afe6-42e5-be46-ea9f11b5ee4a::jetzfcmpeu1b7c100dfkqt29o: "/cert.key": not found
---

Since I don't have the files, so I just proceed to comment them and then I met the next error:

---
failed to solve: archive/tar: unknown file mode ?rwxr-xr-x

---

This happened on airflow-init internal, but I got no idea why it happens nor how to solve it.

By running docker-compose up on /backend/airflow directory, I managed to build the container for the whole project, but I noticed that only the airflow-init is exited, I suppose it should be running as the others did.

Giving that I have problem on docker, so I proceed to try running it on my localhost instead, by running npm install and npm start, I managed to open the frontend, but then I have question about the backend, I wonder if i want to run it locally without docker, how am I suppose to start the backend, as I saw it linked from flask to airflow and so, it would be glad that if you can provide me the steps or solutions on running it on my local machine.

Thanks and regards.

**Comment by arubenruben** [comment]
Hi Lim,
I will split my answer into different comments.

Starting with Docker:
* We acknowledge the problem you reported with docker
* We pushed a new version to the main branch itself that solves the issues you addressed.

The concern was related to the enforcement of the HTTPS protocol. However, you don't need that to execute the code in development.

The changes introduced split the Docker logic into dev and prod files. 
For development, you should now run the dev.docker-compose.yml file.

**Comment by arubenruben** [comment]
Regarding the execution on localhost without Docker:

As far as we know (and this was the first time we used Airflow), the simplest way to execute the stable version of Apache Airflow is to use Docker. Therefore, we encourage you to use dev.docker-compose.yml to simplify your job.

**Comment by arubenruben** [comment]
Despite the new release, solve the questions addressed with Docker. It is important to notice that you still need to set up the database with exercises, medication, and medical conditions.

Some of these materials are subject to copyright; therefore, according to European copyright laws, we can only provide you the scrappers to obtain those materials if Chinese law allows it.

We decided to set up a free database in Mongo Atlas to store the output of the scrapping process. But you are free to select the MongoDB database you intend, as long as you update the.env file accordingly.

**Comment by arubenruben** [comment]
We remember that the code is running in production on physio.inesctec.pt with a small budget of $5. 
But after the budget runs out, the application will become offline.

**Comment by zedonglim** [comment]
Hi @arubenruben,

First, I am sorry for the late response, and thank you for the updates. I highly appreciate it!

I have just tried out the new release with dev.docker-compose.yml file, I guess so far everything is working well as the frontend is able to load up at localhost:3000.

I proceed to test it out by inputting: "I feel pain on my lower back. What can I do?", and I get error message: "Error Sending Question".
For your information, I haven't set up the database with exercises, medication, and medical conditions, so I am wondering is it because of this, that I end up getting that error message?
Or is it because of docker, as I noticed that the there are 2 out of 9 Images in the docker that is not running, in which they are flask and airflow-init respectively, both of them had the status: "Exited". Even after I tried to manually run them again, still exited within few seconds.
I wonder both of them exited is it because I didn't set up the database?

Other than that, I might need some other clarifications, like is there any steps or pre-requisites need to be done before running the dev.docker-compose.yml file or while setting up the .env files?
For example, do I need to establish an environment for Airflow and initialize the required directories before running the dev.docker-compose.yml file, or is it fine just to run dev.docker-compose.yml straight away?
I also noticed about creating a Virtual Environment on the readme file under backend folder, if these are necessary, which should be done first, or what is the order to follow?

As far as I know, there are a total of 4 .env files, which should be placed under backend, airflow, flask and frontend each.
Correct me if I am wrong.
What I want to know is, which variables/fields can be left empty, and which are expected to be filled up?
Especially for the .env file in frontend,
SSL_CRT_FILE=
SSL_KEY_FILE=
PORT=
Well, I am not sure if they are fine just to leave it blank...
Also, while giving value for the variables in .env file, do i need to wrap them between quotation mark or double quotation mark? Or is it fine without the quotation mark?

I am so sorry that I am pretty new to these stuff, so I might have asked some simple questions...

Thanks and regards.

**Comment by arubenruben** [comment]
Hi @zedonglim 

Again, I will split my answer across different comments.

Starting with the Airflow Init exit -> This is the correct behavior. This process exits with exit code 0 after the remaining airflow processes are up and running.

**Comment by arubenruben** [comment]
I'm almost sure that the error code you are getting is related to not setting up the database. 
We adopted Airflow in this project because of its debugging capabilities. You can always access the Airflow GUI on localhost:8000 and sign in with:

user: airflow
pw: airflow

To determine at which step of the pipeline, the algorithm is failing.

If the request is not reaching Airflow, check the logs for the flask Docker container. It is not expected, but a connection error with the flask can happen.

**Comment by arubenruben** [comment]
Regarding the.env files. I believe that, as long as you use the dev. Dockerfile, the problems will not be related to that.

I deeply suggest you back up the database and then reassess if any errors arise.

**Comment by Saschaym** [comment]
> Regarding the execution on localhost without Docker:
> 
> As far as we know (and this was the first time we used Airflow), the simplest way to execute the stable version of Apache Airflow is to use Docker. Therefore, we encourage you to use dev.docker-compose.yml to simplify your job.

**Comment by Saschaym** [comment]
😊
